### ISSUE TITLE
c#  version issues

### ISSUE THREAD

**Issue by 2wong** [kwsch/FlatCrawler#1]
I was trying to reverse the flatbuffers, and I saw your project, it was so helpful to me that it makes it possible to use it without the source protocol files. Similar to proto-raw_data. But there is one point that the net6 version is too high for me to use. Can you give me a lower version to use, thank you

**Comment by kwsch** [comment]
You can always try downgrading the net6.0 references in the `csproj` and try recompiling. Not sure what version you're trying to target.

Visual Studio 2022 Community supports net6.0, but I suppose changing to net5.0 will still compile.

**Comment by 2wong** [comment]
I changed the csproj file according to your method, but it still doesn't work. My Visual Studio version is 2019. After the project is loaded, many syntax errors are displayed. It seems that 2019 does not support c#9. Please help me. .
I have binary stream now and want to convert flatbuffer to human readable through your project, and I don't have protocol source file (Schema)

**Comment by 2wong** [comment]
> You can always try downgrading the net6.0 references in the `csproj` and try recompiling. Not sure what version you're trying to target.
> 
> Visual Studio 2022 Community supports net6.0, but I suppose changing to net5.0 will still compile.

Thanks for your reply, I solved the above problem. But when I try to parse the binary file, an error occurs.
For example: 2c000000f7020000956ed5000c00000008000800000004000800000004000000010000007e2c220900000000
, in solving the above binary stream has been unable to parse, I want to parse it into a human-readable json mode, what am I wrong?

**Comment by 2wong** [comment]
> You can always try downgrading the net6.0 references in the `csproj` and try recompiling. Not sure what version you're trying to target.
> 
> Visual Studio 2022 Community supports net6.0, but I suppose changing to net5.0 will still compile.

Thanks for your reply, I solved the above problem. But when I try to parse the binary, I have some problems. I want to parse it into human readable json , which function should I call please?

**Comment by kwsch** [comment]
> Thanks for your reply, I solved the above problem. But when I try to parse the binary, I have some problems. I want to parse it into human readable json , which function should I call please?

This program does not automatically guess the types of each field, or the amount of fields for each object. The program just lets you manually crawl the data so you can document the data structure yourself, without having to juggle the raw data.

Once you've documented the schema sufficiently, there are other tools. The flatc.exe has command line arguments to accept a binary, a schema, and will write a json for you. I've also used FlatSharp to read and write documented FlatBuffers in other projects like pkNX.
